version: "3.9"
services:
  web:
    build: .
    container_name: web
    ports:
      - "8080:80"
  db: 
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports: 
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config: