version: "3.9"
services:
  web:
    build: .
    container_name: web
    ports:
      - "8080:80"
  db:
    platform: linux/x86_64
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: